// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enhancements.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEnhancement = `-- name: CreateEnhancement :one
INSERT INTO enhancements (faction_id, name, enhancement_type, description, points, version, source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, faction_id, name, enhancement_type, description, points, is_unique, version, source, created_at, updated_at
`

type CreateEnhancementParams struct {
	FactionID       uuid.UUID
	Name            string
	EnhancementType string
	Description     string
	Points          int32
	Version         string
	Source          string
}

func (q *Queries) CreateEnhancement(ctx context.Context, arg CreateEnhancementParams) (Enhancement, error) {
	row := q.db.QueryRow(ctx, createEnhancement,
		arg.FactionID,
		arg.Name,
		arg.EnhancementType,
		arg.Description,
		arg.Points,
		arg.Version,
		arg.Source,
	)
	var i Enhancement
	err := row.Scan(
		&i.ID,
		&i.FactionID,
		&i.Name,
		&i.EnhancementType,
		&i.Description,
		&i.Points,
		&i.IsUnique,
		&i.Version,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnhancement = `-- name: DeleteEnhancement :exec
DELETE FROM enhancements
WHERE id = $1
`

func (q *Queries) DeleteEnhancement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnhancement, id)
	return err
}

const getEnhancementByID = `-- name: GetEnhancementByID :one
SELECT id, faction_id, name, enhancement_type, description, points, is_unique, version, source, created_at, updated_at
FROM enhancements
WHERE id = $1
`

func (q *Queries) GetEnhancementByID(ctx context.Context, id uuid.UUID) (Enhancement, error) {
	row := q.db.QueryRow(ctx, getEnhancementByID, id)
	var i Enhancement
	err := row.Scan(
		&i.ID,
		&i.FactionID,
		&i.Name,
		&i.EnhancementType,
		&i.Description,
		&i.Points,
		&i.IsUnique,
		&i.Version,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnhancements = `-- name: GetEnhancements :many
SELECT id, faction_id, name, enhancement_type, description, points, is_unique, version, source, created_at, updated_at
FROM enhancements
ORDER BY faction_id, name ASC
`

func (q *Queries) GetEnhancements(ctx context.Context) ([]Enhancement, error) {
	rows, err := q.db.Query(ctx, getEnhancements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enhancement
	for rows.Next() {
		var i Enhancement
		if err := rows.Scan(
			&i.ID,
			&i.FactionID,
			&i.Name,
			&i.EnhancementType,
			&i.Description,
			&i.Points,
			&i.IsUnique,
			&i.Version,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnhancementsByType = `-- name: GetEnhancementsByType :many
SELECT id, faction_id, name, enhancement_type, description, points, is_unique, version, source, created_at, updated_at
FROM enhancements
WHERE enhancement_type = $1
ORDER BY faction_id, name ASC
`

func (q *Queries) GetEnhancementsByType(ctx context.Context, enhancementType string) ([]Enhancement, error) {
	rows, err := q.db.Query(ctx, getEnhancementsByType, enhancementType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enhancement
	for rows.Next() {
		var i Enhancement
		if err := rows.Scan(
			&i.ID,
			&i.FactionID,
			&i.Name,
			&i.EnhancementType,
			&i.Description,
			&i.Points,
			&i.IsUnique,
			&i.Version,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnhancementsForFaction = `-- name: GetEnhancementsForFaction :many
SELECT id, faction_id, name, enhancement_type, description, points, is_unique, version, source, created_at, updated_at
FROM enhancements
WHERE faction_id = $1
ORDER BY name ASC
`

func (q *Queries) GetEnhancementsForFaction(ctx context.Context, factionID uuid.UUID) ([]Enhancement, error) {
	rows, err := q.db.Query(ctx, getEnhancementsForFaction, factionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enhancement
	for rows.Next() {
		var i Enhancement
		if err := rows.Scan(
			&i.ID,
			&i.FactionID,
			&i.Name,
			&i.EnhancementType,
			&i.Description,
			&i.Points,
			&i.IsUnique,
			&i.Version,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnhancement = `-- name: UpdateEnhancement :one
UPDATE enhancements
SET name = $2, enhancement_type = $3, description = $4, points = $5, version = $6, source = $7, updated_at = now()
WHERE id = $1
RETURNING id, faction_id, name, enhancement_type, description, points, is_unique, version, source, created_at, updated_at
`

type UpdateEnhancementParams struct {
	ID              uuid.UUID
	Name            string
	EnhancementType string
	Description     string
	Points          int32
	Version         string
	Source          string
}

func (q *Queries) UpdateEnhancement(ctx context.Context, arg UpdateEnhancementParams) (Enhancement, error) {
	row := q.db.QueryRow(ctx, updateEnhancement,
		arg.ID,
		arg.Name,
		arg.EnhancementType,
		arg.Description,
		arg.Points,
		arg.Version,
		arg.Source,
	)
	var i Enhancement
	err := row.Scan(
		&i.ID,
		&i.FactionID,
		&i.Name,
		&i.EnhancementType,
		&i.Description,
		&i.Points,
		&i.IsUnique,
		&i.Version,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
