// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: keywords.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addKeywordToUnit = `-- name: AddKeywordToUnit :exec
INSERT INTO unit_keywords (unit_id, keyword_id, value)
VALUES ($1, $2, $3)
`

type AddKeywordToUnitParams struct {
	UnitID    uuid.UUID
	KeywordID uuid.UUID
	Value     pgtype.Text
}

func (q *Queries) AddKeywordToUnit(ctx context.Context, arg AddKeywordToUnitParams) error {
	_, err := q.db.Exec(ctx, addKeywordToUnit, arg.UnitID, arg.KeywordID, arg.Value)
	return err
}

const createKeyword = `-- name: CreateKeyword :one
INSERT INTO keywords (name)
VALUES ($1)
RETURNING id, game_id, name, description, version, source, created_at, updated_at
`

func (q *Queries) CreateKeyword(ctx context.Context, name string) (Keyword, error) {
	row := q.db.QueryRow(ctx, createKeyword, name)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllKeywords = `-- name: GetAllKeywords :many
SELECT id, game_id, name, description, version, source, created_at, updated_at FROM keywords 
ORDER BY name ASC
`

func (q *Queries) GetAllKeywords(ctx context.Context) ([]Keyword, error) {
	rows, err := q.db.Query(ctx, getAllKeywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keyword
	for rows.Next() {
		var i Keyword
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeywordsForUnit = `-- name: GetKeywordsForUnit :many
SELECT k.id, k.name, uk.value
FROM keywords k
JOIN unit_keywords uk ON uk.keyword_id = k.id
WHERE uk.unit_id = $1
ORDER BY k.name ASC
`

type GetKeywordsForUnitRow struct {
	ID    uuid.UUID
	Name  string
	Value pgtype.Text
}

func (q *Queries) GetKeywordsForUnit(ctx context.Context, unitID uuid.UUID) ([]GetKeywordsForUnitRow, error) {
	rows, err := q.db.Query(ctx, getKeywordsForUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKeywordsForUnitRow
	for rows.Next() {
		var i GetKeywordsForUnitRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitsWithKeyword = `-- name: GetUnitsWithKeyword :many
SELECT u.id, u.faction_id, u.name, u.points, u.move, u.health, u.save, u.ward, u.control, u.rend, u.attacks, u.damage, u.summon_cost, u.banishment, u.is_manifestation, u.min_size, u.max_size, u.version, u.source, u.created_at, u.updated_at
FROM units u
JOIN unit_keywords uk ON uk.unit_id = u.id
JOIN keywords k ON k.id = uk.keyword_id
WHERE k.name = $1
ORDER BY u.name ASC
`

func (q *Queries) GetUnitsWithKeyword(ctx context.Context, name string) ([]Unit, error) {
	rows, err := q.db.Query(ctx, getUnitsWithKeyword, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.FactionID,
			&i.Name,
			&i.Points,
			&i.Move,
			&i.Health,
			&i.Save,
			&i.Ward,
			&i.Control,
			&i.Rend,
			&i.Attacks,
			&i.Damage,
			&i.SummonCost,
			&i.Banishment,
			&i.IsManifestation,
			&i.MinSize,
			&i.MaxSize,
			&i.Version,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitsWithKeywordAndValue = `-- name: GetUnitsWithKeywordAndValue :many
SELECT u.id, u.faction_id, u.name, u.points, u.move, u.health, u.save, u.ward, u.control, u.rend, u.attacks, u.damage, u.summon_cost, u.banishment, u.is_manifestation, u.min_size, u.max_size, u.version, u.source, u.created_at, u.updated_at
FROM units u
JOIN unit_keywords uk ON uk.unit_id = u.id
JOIN keywords k ON k.id = uk.keyword_id
WHERE k.name = $1
  AND uk.value = $2
ORDER BY u.name ASC
`

type GetUnitsWithKeywordAndValueParams struct {
	Name  string
	Value pgtype.Text
}

func (q *Queries) GetUnitsWithKeywordAndValue(ctx context.Context, arg GetUnitsWithKeywordAndValueParams) ([]Unit, error) {
	rows, err := q.db.Query(ctx, getUnitsWithKeywordAndValue, arg.Name, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.FactionID,
			&i.Name,
			&i.Points,
			&i.Move,
			&i.Health,
			&i.Save,
			&i.Ward,
			&i.Control,
			&i.Rend,
			&i.Attacks,
			&i.Damage,
			&i.SummonCost,
			&i.Banishment,
			&i.IsManifestation,
			&i.MinSize,
			&i.MaxSize,
			&i.Version,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeKeywordFromUnit = `-- name: RemoveKeywordFromUnit :exec
DELETE FROM unit_keywords
WHERE unit_id = $1 AND keyword_id = $2
`

type RemoveKeywordFromUnitParams struct {
	UnitID    uuid.UUID
	KeywordID uuid.UUID
}

func (q *Queries) RemoveKeywordFromUnit(ctx context.Context, arg RemoveKeywordFromUnitParams) error {
	_, err := q.db.Exec(ctx, removeKeywordFromUnit, arg.UnitID, arg.KeywordID)
	return err
}
