// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Ability struct {
	ID          uuid.UUID
	UnitID      pgtype.UUID
	FactionID   pgtype.UUID
	Name        string
	Description pgtype.Text
	Type        pgtype.Text
	Phase       pgtype.Text
	Version     pgtype.Text
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type AbilityEffect struct {
	ID          uuid.UUID
	AbilityID   uuid.UUID
	Stat        string
	Modifier    int32
	Condition   pgtype.Text
	Description pgtype.Text
	Version     pgtype.Text
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type BattleFormation struct {
	ID          uuid.UUID
	GameID      uuid.UUID
	FactionID   uuid.UUID
	Name        string
	Description pgtype.Text
	Version     pgtype.Text
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Enhancement struct {
	ID          uuid.UUID
	FactionID   uuid.UUID
	Name        string
	Description pgtype.Text
	Points      pgtype.Int4
	Version     pgtype.Text
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Faction struct {
	ID         uuid.UUID
	GameID     uuid.UUID
	Name       string
	Allegiance pgtype.Text
	Version    pgtype.Text
	Source     pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Game struct {
	ID        uuid.UUID
	Name      string
	Edition   string
	Version   pgtype.Text
	Source    pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Keyword struct {
	ID          uuid.UUID
	GameID      pgtype.UUID
	Name        string
	Description pgtype.Text
	Version     pgtype.Text
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Rule struct {
	ID          uuid.UUID
	GameID      uuid.UUID
	Name        string
	Description string
	RuleType    pgtype.Text
	Version     pgtype.Text
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Unit struct {
	ID              uuid.UUID
	FactionID       uuid.UUID
	Name            string
	Points          pgtype.Int4
	Move            pgtype.Text
	Health          pgtype.Int4
	Save            pgtype.Text
	Ward            pgtype.Text
	Control         pgtype.Int4
	Rend            pgtype.Text
	Attacks         pgtype.Text
	Damage          pgtype.Text
	SummonCost      pgtype.Text
	Banishment      pgtype.Text
	IsManifestation pgtype.Bool
	MinSize         int32
	MaxSize         int32
	Version         pgtype.Text
	Source          pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type UnitKeyword struct {
	UnitID    uuid.UUID
	KeywordID uuid.UUID
	Value     pgtype.Text
}

type Weapon struct {
	ID        uuid.UUID
	UnitID    uuid.UUID
	Name      string
	Range     pgtype.Text
	Attacks   pgtype.Text
	ToHit     pgtype.Text
	ToWound   pgtype.Text
	Rend      pgtype.Text
	Damage    pgtype.Text
	Version   pgtype.Text
	Source    pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
