// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Ability struct {
	ID          uuid.UUID
	UnitID      uuid.UUID
	FactionID   uuid.UUID
	Name        string
	Description string
	Type        string
	Phase       string
	Version     string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AbilityEffect struct {
	ID          uuid.UUID
	AbilityID   uuid.UUID
	Stat        string
	Modifier    int32
	Condition   string
	Description string
	Version     string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BattleFormation struct {
	ID          uuid.UUID
	GameID      uuid.UUID
	FactionID   uuid.UUID
	Name        string
	Description string
	Version     string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Enhancement struct {
	ID              uuid.UUID
	FactionID       uuid.UUID
	Name            string
	EnhancementType string
	Description     string
	Points          int32
	Version         string
	Source          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Faction struct {
	ID         uuid.UUID
	GameID     uuid.UUID
	Name       string
	Allegiance string
	Version    string
	Source     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Game struct {
	ID        uuid.UUID
	Name      string
	Edition   string
	Version   string
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Keyword struct {
	ID          uuid.UUID
	GameID      uuid.UUID
	Name        string
	Description string
	Version     string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Rule struct {
	ID          uuid.UUID
	GameID      uuid.UUID
	Name        string
	Description string
	Text        string
	RuleType    string
	Version     string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Unit struct {
	ID              uuid.UUID
	FactionID       uuid.UUID
	Name            string
	Description     string
	IsManifestation bool
	Move            int32
	Health          int32
	Save            string
	Ward            string
	Control         int32
	Points          int32
	SummonCost      string
	Banishment      string
	MinSize         int32
	MaxSize         int32
	MatchedPlay     bool
	Version         string
	Source          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UnitKeyword struct {
	UnitID    uuid.UUID
	KeywordID uuid.UUID
	Value     string
}

type Weapon struct {
	ID        uuid.UUID
	UnitID    uuid.UUID
	Name      string
	Range     string
	Attacks   string
	ToHit     string
	ToWound   string
	Rend      string
	Damage    string
	Version   string
	Source    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
