run:
  timeout: 5m
  skip-dirs:
    - vendor
    - bin

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - unused
    - gosimple
  disable:
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
    
    - text: "should be"
      linters:
        - golint
