run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gosec
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - govet
    - ineffassign

linters-settings:
  gosec:
    excludes:
      - G115
      - G304

issues:
  exclude-dirs:
    - tmp
    - bin
