version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # We leave this empty to use the standard defaults 
  # This prevents "unknown linter" errors
  enable-all: false
  disable-all: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
