DROP TABLE IF EXISTS rules CASCADE;
DROP TABLE IF EXISTS abilities CASCADE;
DROP TABLE IF EXISTS weapons CASCADE;
DROP TABLE IF EXISTS units CASCADE;
DROP TABLE IF EXISTS factions CASCADE;
DROP TABLE IF EXISTS games CASCADE;

DROP EXTENSION IF EXISTS "pgcrypto";
